### PR TITLE
Two small tweaks to Vue branch.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by dannon** [comment]
The formatted reference change makes sense, but gulp should never be touching .vue files.  What was breaking there?

**Comment by jmchilton** [comment]
Want to just cherry-pick that one then?

It wasn't seeming to trigger a rebuild when I did ``client-watch`` and touched a vue file - maybe I was just crazy though?

**Comment by dannon** [comment]
Sure, I'll cherrypick that over.  The webpack watching rebuilds take a bit longer currently due to the multiple bundles (which I'm going to refactor and improve post-vacation).  You may just not have waited long enough?

**Comment by jmchilton** [comment]
Ahh - that is probably it - I got used to seeing certain things and it taking certain amounts of time. Thanks @dannon.

**Pull request closed without merging**
