### PR TITLE
Run qunit tests under Karma.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by dannon** [comment]
Whoa, awesome!  That was fast.

**Comment by dannon** [comment]
I'll work on the kinks you mention in the config today.

**Comment by jmchilton** [comment]
I realized some of the problems - like the bibtex stuff was just that ``lib`` is not complete by default anymore (a very good thing) and so ``make client`` I guess should be run before ``make test``.

Here is a commit that adds babel to the tests and starts to convert them to ES6 https://github.com/jmchilton/galaxy/commit/e9319704e0622497a503675fa68df42ca326323a - I'm not sure if we want that long term and that is helpful to try to solve some of these problems or if that is just a complication that causes more problems before we've solved the other ones.

**Comment by dannon** [comment]
@jmchilton Cool, thanks, I'll take a look at that commit!

**Comment by jmchilton** [comment]
Thanks for the emrge - I opened a PR for a better commit I think. I've convinced myself we can get the tests working with adding babel to the tests - so I'd leave off the jmchilton/galaxy@e931970 work until a subsequent PR.

Have a good weekend.

**Pull request merged**
